version: '3.7'

services:

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management
    networks:
      - spring-cloud-network
    environment:
      - RABBITMQ_DEFAULT_USER=username
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - '5672:5672'
      - '15672:15672'

  postgres:
    container_name: postgres
    image: postgres
    networks:
      - spring-cloud-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      PGDATA: "/data/postgres"
    volumes:
        - ./postgre_init.sql:/docker-entrypoint-initdb.d/postgre_init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  cargoservice:
    restart: always
    image: emrahozturk/guavapay:cargoservice
    build:
      context: ./cargoService
      dockerfile: Dockerfile
    networks:
      - spring-cloud-network
    ports:
      - '8013:8013'
    environment:
      POSTGRES: postgres
      RABBITMQ: rabbitmq

  orderservice:
    restart: always
    image: emrahozturk/guavapay:orderservice
    build:
      context: ./orderService
      dockerfile: Dockerfile
    networks:
      - spring-cloud-network
    ports:
      - '8012:8012'
    environment:
      POSTGRES: postgres
      RABBITMQ: rabbitmq

  authenticationservice:
    restart: always
    image: emrahozturk/guavapay:authenticationservice
    build:
      context: ./authService
      dockerfile: Dockerfile
    networks:
      - spring-cloud-network
    ports:
      - '8011:8011'
    environment:
      POSTGRES: postgres
      RABBITMQ: rabbitmq

  gateway:
    restart: always
    image: emrahozturk/guavapay:gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    networks:
      - spring-cloud-network
    ports:
      - '8010:8010'
    environment:
      AUTHENTICATION_SERVICE: authenticationservice
      ORDER_SERVICE: orderservice
      CARGO_SERVICE: cargoservice

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - spring-cloud-network
    ports:
      - "4200:80"
    environment:
      GATEWAY: localhost

networks:
  spring-cloud-network:
    driver: bridge