server:
  port: 8010

jwt:
  secret: secretkey
  token:
    validity: 1000

service:
  authentication: http://${AUTHENTICATION_SERVICE}:8011/authentication
  order: http://${ORDER_SERVICE}:8012/order
  cargo: http://${CARGO_SERVICE}:8013/cargo